### ISSUE TITLE
Adding git tag to PR's that are release

### ISSUE THREAD

**Issue by vittalas** [semantic-release/github#179]
Hi,

I am looking at adding a git tag information that the PR was released as a label against the PR. Currently every PR that is released gets the label "released" and i am looking for something like adding a git tag number as well as a label. Could not find any information in the docs and this would be nice to have for us.

Thanks !

**Comment by gr2m** [comment]
It’s not implemented, you’d need to implement a plugin yourself:
https://semantic-release.gitbook.io/semantic-release/extending/plugins-list

But I would recommend against doing that. The problem is that it would create a lot of new labels which will make it hard to select standard labels like "feature" or "bug" or "question"

**Comment by vittalas** [comment]
thanks @gr2m ! also this link does not work for me : https://semantic-release.gitbook.io/semantic-release/extending/plugins-list i see a 404

**Comment by pvdlg** [comment]
This is already supported in beta via the [option `releasedLabels`](https://github.com/semantic-release/github/tree/beta#releasedlabels). You can add any label you'd like to the PRs on release and construct the label with any variable.
