### ISSUE TITLE
[Feature request] Able to ignore bots for posting comments/tagging issues

### ISSUE THREAD

**Issue by Belphemur** [semantic-release/github#529]
Hello,

In most of my repository, I have dependabot enabled (with auto-merge after test passes), a lot of the lib get updated quite a lot and I end up with a lot PR relating to dependencies update.

When it's time to do a release, semantic-release/github will go and post a comments on all those PR... This spam me aquite a lot.
I love the feature of posting comments (especially for human made PR or Issue), but can we disable it for bots ?

Having a blacklist of users would be great !

**Comment by xeger** [comment]
Yes, please!

Formerly, I could rely on GitHub Notifications to inform me when another human needed action from me: they wanted a review; they had feedback; they opened a bug; etc.

Currently I work in an organization that posts comments to PRs during GitHub Actions workflows, and also has bots that post comments (and they even @ me).

I need a way to ignore the "bot spam" so that I can once again be responsive to humans who need me.

And/or, GitHub needs to provide a place _other_ than in comments for bots to record high-volume information. (Annotations and checks are not sufficient for the voluminous output that our SSAE-16 compliance requires.)

**Comment by babblebey** [comment]
When https://github.com/semantic-release/github/pull/874/ merges, you will have the ability to configure this using the property `successCommentCondition` as stated in this comment https://github.com/semantic-release/github/pull/874/#issuecomment-2292206401

> ```js
> successCommentCondition: "<% return !issue.user || issue.user.type !== 'Bot'; %>"
> // This adds comment/label to all issues (regardless of user) and pull request created by users (ignoring bots)
> ```

😉

**Comment by babblebey** [comment]
When https://github.com/semantic-release/github/pull/874/ merges, you will have the ability to configure this using the property `successCommentCondition` as stated in this comment https://github.com/semantic-release/github/pull/874/#issuecomment-2292206401

> ```js
> successCommentCondition: "<% return !issue.user || issue.user.type !== 'Bot'; %>"
> // This adds comment/label to all issues (regardless of user) and pull request created by users (ignoring bots)
> ```

😉

**Comment by babblebey** [comment]
> When #874 merges, you will have the ability to configure this using the property `successCommentCondition` as stated in this comment #874
> 
> > ```js
> > successCommentCondition: "<% return !issue.user || issue.user.type !== 'Bot'; %>"
> > // This adds comment/label to all issues (regardless of user) and pull request created by users (ignoring bots)
> > ```
> 
> 😉

**A quick update on this:** Now you can target and ignore both issues and PRs created by bot by simply setting your `successCommentCondition`

> ```js
> successCommentCondition: "<% return issue.user.type !== 'Bot'; %>"
> ```
