### ISSUE TITLE
Release to different github repo?

### ISSUE THREAD

**Issue by simlu** [semantic-release/github#81]
Is there a way to release to a different github repository? What would be required to add that functionality? 

Cheers, L~

**Comment by pvdlg** [comment]
The core concept of semantic-release implies:
- Analyzing commits since the last commit to determine the release version
- Tag the last commit used for the release so next time semantic-release runs it will be able to figure which commits are new

That mean the release (at least the tag part) has to be done on the same repo.
Now, as long as you continue to create the tag on the repo containing the source code and the commits (which is handled by the core), you can create a plugin to do whatever you like on any repo.

Releasing to a different repo is probably not something we would implement in the core nor in the `@semantic-release/xxx` plugins unless we have a very good case for it. That means explaining why it would be a good feature that would benefit a large part of the semantic-release users.

The best solution for you is probably to implement a plugin.

**Comment by simlu** [comment]
Sweet, thank you very much for the reply! 

Our use case is that we have a private repo, but we want to submit a release with the build artifact (but without the source code), to a separate public repo.

We'll look into creating a plugin. Would you recommend using this plugin as a base and altering it?

Is there documentation on how plugins are structured and how to write them?

Thanks again for your reply!

**Comment by pvdlg** [comment]
It depends on what you want to do exactly. GitHub releases are associated with a tag (therefore associated with a commit). By definition the concept of GitHub release imply doing them on the repo on which you push your commits.
I don't know if what you try to achieve is even possible. So I don't know if it's a good idea to start with this plugin or not. Anyway the code is fairly simple so feel free to look at it.

There is no documentation regarding writing a plugin yet. It's in my todo list.

**Comment by pvdlg** [comment]
I'm closing as this won't be implemented in this plugin. Feel free to continue to conversation though.

**Comment by simlu** [comment]
Thank you very much for your input. We eventually decided to go down a different path and use a custom ci script after semantic release has successfully published to the current repo. Thanks again for all your work!
