### ISSUE TITLE
How to configure protected release branch

### ISSUE THREAD

**Issue by kopax** [semantic-release/github#84]
We are using `@semantic-release/github` and we would like to know the recommended configuration to work with protection:

Our release branch is `master`,

So far we did try to protect using: 

```bash
  body='{
    "required_status_checks": {
      "strict":true,
      "contexts": [
        "continuous-integration/travis-ci"
      ]
    },
    "enforce_admins": true,
    "required_pull_request_reviews": null,
    "restrictions": {
        "users": [
          "kopax"
        ],
        "teams": [
          "developers"
        ]
    }
  }'

  curl -sS -L -X PUT \
    -H "Authorization: token ${GH_TOKEN:-$GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.luke-cage-preview+json" \
    "https://api.github.com/repos/${scope}/${name}/branches/dev/protection" \
  --compressed \
  --data-binary "$body"
  curl -sS -L -X PUT \
    -H "Authorization: token ${GH_TOKEN:-$GITHUB_TOKEN}" \
    -H "Accept: application/vnd.github.luke-cage-preview+json" \
    "https://api.github.com/repos/${scope}/${name}/branches/master/protection" \
  --compressed \
  --data-binary "$body"
```

We get the following error:

```bash
{ Error: Command failed: git push --tags https://[secure]@github.com/yeutech-lab/accept-dot-path.git HEAD:master
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: Required status check "continuous-integration/travis-ci" is expected.        
To https://github.com/yeutech-lab/accept-dot-path.git
 ! [remote rejected] HEAD -> master (protected branch hook declined)
```

I assume we should disable travis ci check, but that seems a bit odd decision, how do you users of `semantic-release` recommand to configure the protection on GitHub?

**Comment by pvdlg** [comment]
As explain in the doc, semantic-release just require push access to your repo to push the release tag: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication

As you can see from your logs the command `git push --tags https://<GH_
TOKEN>@github.com/yeutech-lab/accept-dot-path.git HEAD:master` fails so the users associated with your token doesn't have the permission to push.

In all semantic-release repos we have the `master` branch set as protected and everything works as expected:
![protected_branch_-_caribou](https://user-images.githubusercontent.com/3250552/41942033-ec32dc08-796b-11e8-85e2-2ff89c671705.jpg)

I guess your problem is somewhere else or is related to a configuration you didn't mention.

**Comment by pvdlg** [comment]
I'm closing as no response or further questions were added to the thread, so I assume the response provided solved the issue. Feel free to re-open otherwise.

**Comment by kopax** [comment]
@pvdlg we have not tried yet and we are waiting the end of all our test stage to test this as I believe we are having issue because of this. Thanks for your answer which gived us the correct configuration.
