### ISSUE TITLE
Potentially breaking change introduced in #897 - clarification needed

### ISSUE THREAD

**Issue by dominykas** [semantic-release/github#914]
https://github.com/semantic-release/github/pull/897 introduces a requirement for the token to be associated with a [user that has `maintain` permission](https://github.com/semantic-release/github/blame/439357863db95ef5efdd7b271398d8355b571532/lib/verify.js#L140).

That was not necessary in the past, and should probably be considered a breaking change? 

Moreover, we've never had issues with just the `push` permissions - not sure if there was any specific rationale around it? This was [picked up in the review](https://github.com/semantic-release/github/pull/897#discussion_r1733571651), and noted as "probably can't write issues, releases and pull requests" - but I'm not sure that's the case - the standard `push` permissions gives most of that access?

I'm also not 100% certain how that maps to the concept of roles and _actual_ permissions in Github - it is possible to set things up in such a way that roles have different permissions, so quite possibly the naive `maintain` check is not enough and needs explicit checks for specific API access?

When the user does not have the `maintain` permission, it then [performs the check to `HEAD /installation/repositories`](https://github.com/semantic-release/github/blame/439357863db95ef5efdd7b271398d8355b571532/lib/verify.js#L147) - however that is only necessary when running as an app. If `semantic-release` is running inside e.g. Jenkins - then this check does not make sense, as generally `semantic-release` does not need to "List repositories accessible to the app installation" anyways to perform a release?

**Comment by jedwards1211** [comment]
oof, sorry about that, sure wish the GitHub API just gave us a method to check that the token has the exact permissions we need

**Comment by jedwards1211** [comment]
> I'm also not 100% certain how that maps to the concept of roles and actual permissions in Github - it is possible to set things up in such a way that roles have different permissions

I'm pretty sure this is possible with fine-grained PATs at least, but unfortunately it's impossible to determine the scopes of a fine-grained PAT with the existing API, the best you can do is try requests and see if they succeed

**Comment by jedwards1211** [comment]
@travi @babblebey it should work if we keep everything in the PR except the check for `maintain` permission.  I was looking back through the GitHub docs and I realized my mistake.  The [table of repository role permissions](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization#permissions-for-each-role) lists:
- Read
- Triage
- Write
- Maintain
- Admin

I got confused because the [Get a repository method](https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository) lists:
- `pull`
- `triage`
- `push`
- `maintain`
- `admin`

I mistakenly assumed `push` was merely permission to push, not one of the roles in the first list, but now I realize, `push` must correspond to Write and `pull` must correspond to Read...argh.  And as OP mentions, Write AKA `push` does have permission to write issues and releases according to the table.

Do you want me to make a new PR with everything but the `maintain` check?

@gr2m I wish the Get a repository API method had explicit documentation about the `permissions` subfields.

**Comment by jedwards1211** [comment]
@dominykas I just reread this more carefully:

> it is possible to set things up in such a way that roles have different permissions

From what I can see, there are just a few limitations that can be configured for repository roles in an organization -- it doesn't look like it's possible to remove permission to push commits, edit issues, releases, or pull requests from the `push` role.  If you have seen documentation that contradicts this please let me know.

**Comment by dominykas** [comment]
> If you have seen documentation that contradicts this please let me know.

I'll admit that I haven't looked into this in detail - I just know that it's possible to make some changes there.

Thanks for looking into this!
