### ISSUE TITLE
How should rate limiting errors be handled?

### ISSUE THREAD

**Issue by mike-north** [semantic-release/github#98]
I've run into a couple of situations where I'm bumping a few libraries quickly enough that I seem to hit the github API rate limit by the time semantic-release needs to do its thing. The current mode of failure is
* The build passes
* No npm release is published
* No github release is published
* I receive no indication whatsoever that a problem has been encountered

Once I'm in this state, someone usually comes up to me and tells me that no release was cut. 

I think that a rate limit error should fail the build, so that when the github account comes out of the rate limit window, it can be manually restarted to attempt the same release again.

As it stands, I end up waiting for a half hour and making a trivial commit of some sort in order to trigger a new patch release.

**Comment by pvdlg** [comment]
A rate limit error would definitely make semantic-release to errors out.
I guess it depends on how you configure your CI.

Can you provide the CI logs when the problem happens, your CI config and the semantic-release config?

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/travis-build-stages.md#multiple-node-jobs-configuration:
> It's recommended to run the semantic-release command in the Travis deploy step so if an error occurs the build will fail and Travis will send a notification.

This way your build will fail if an error happens.

semantic-release also normally inform you of a failure by opening an issue on GitHub. However on that specific case it doesn't work as you don't have API call remaining for you user.

Handling `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset` should be added to the GitHub API client at some point. So that would solve your issue (semantic-release will just wait until the available calls are reset).

I would strongly recommend you to create a dedicated user for semantic-release. This way it will have it's dedicated 5000 calls per hour rather than sharing it with the other things you do with the API.

**Comment by mike-north** [comment]
Thanks so much for pointing me in the right direction @pvdlg! As I said, my CI config was generated from `semantic-release/cli`.

https://github.com/semantic-release/cli/blob/a7202dd78a2166066a3b7dd132de48f51708dfcc/src/lib/travis.js#L25

Do you feel that the default should be to run `semantic-release` in the Travis `deploy` step instead of the current `after_success` step?

**Comment by mike-north** [comment]
Another question regarding rate limiting -- I suspect that my one github user's 5K call-per-hour allowance is being largely consumed by semantic-release. In particular, this may be due to my CI pipelines running tests against several node/library versions.

Are steps taken to ensure these calls aren't wasted? For example if I'm testing against Node 6, 8, 9 and 10 -- is the commit log analyzed **on each CI job** (each node version in my case)? If so, it seems like this may be redundant work.

**Comment by pvdlg** [comment]
> Do you feel that the default should be to run semantic-release in the Travis deploy step instead of the current after_success step?

Yes it should be in `deploy` and you should use Travis Build Stages rather than `travis-deploy-once`. The cli setup is not well maintained right now unfortunately.

> Another question regarding rate limiting -- I suspect that my one github user's 5K call-per-hour allowance is being largely consumed by semantic-release. In particular, this may be due to my CI pipelines running tests against several node/library versions.

semantic-release doesn't use the GitHub API during your tests. It's only only when making a release.
So the number of version of Node you are testing on is irrelevant.

semantic-release call the GitHub API to:
- Verify the token has permission on the repo
- Create Release
- Search for issues/PR fixed within the release
- Add comment on those to indicate they have been solved in the release

What I see from your CI logs is that the Rate limit error happened when verifying the permission which is the very first call semantic-release does. So your 5000 calls per hours were depleted even before semantic-release started.

> Are steps taken to ensure these calls aren't wasted? For example if I'm testing against Node 6, 8, 9 and 10 -- is the commit log analyzed on each CI job (each node version in my case)? If not, it seems like this may be redundant work.

semantic-release runs only after all your tests on all Node version are successful. No matter on how many Node version you test, semantic-release runs once. As indicated above, GitHub calls are made only if a release has to be published.
